[module]
module.name = "Numbers\Tenants\Widgets\Batches"
module.code = "TM-Widget-Batches"
module.title = "Batches Widget"
module.version = "1.0.0"

[dependencies]
dep.submodule.Numbers.Backend.Db.__any = 1
dep.submodule.Numbers.Tenants.Tenants = 1

; --- models (name and parent class) ---
dep.model.\Numbers\Tenants\Widgets\Batches\Model\Types = "\Object\Table"
dep.model.\Numbers\Tenants\Widgets\Batches\Model\Entries = "\Object\Table"
dep.model.\Numbers\Tenants\Widgets\Batches\Model\Records = "\Object\Table"

; imports
dep.model.\Numbers\Tenants\Widgets\Batches\Data\System = "\Object\Import"

[help]
; Batches Widget
